"""0002 add rating

Revision ID: 30936cafabda
Revises: ffb61b5edd0c
Create Date: 2026-03-06 16:04:39.987913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30936cafabda'
down_revision = 'ffb61b5edd0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
